### YamlMime:ManagedReference
items:
- uid: StansAssets.Foundation.ScriptableSettingsSingleton`1
  commentId: T:StansAssets.Foundation.ScriptableSettingsSingleton`1
  id: ScriptableSettingsSingleton`1
  parent: StansAssets.Foundation
  children:
  - StansAssets.Foundation.ScriptableSettingsSingleton`1.Instance
  - StansAssets.Foundation.ScriptableSettingsSingleton`1.Save
  - StansAssets.Foundation.ScriptableSettingsSingleton`1.UpdateVersion(System.String)
  - StansAssets.Foundation.ScriptableSettingsSingleton`1.Version
  langs:
  - csharp
  - vb
  name: ScriptableSettingsSingleton<T>
  nameWithType: ScriptableSettingsSingleton<T>
  fullName: StansAssets.Foundation.ScriptableSettingsSingleton<T>
  type: Class
  source:
    id: ScriptableSettingsSingleton
    path: ''
    startLine: 103
  assemblies:
  - cs.temp.dll
  namespace: StansAssets.Foundation
  summary: "\nThis class simplifies a singleton pattern implementation,\nthat can be used with classes extended from a ScriptableObject.\n"
  example: []
  syntax:
    content: 'public abstract class ScriptableSettingsSingleton<T> : ScriptableSettings where T : ScriptableSettings'
    typeParameters:
    - id: T
    content.vb: >-
      Public MustInherit Class ScriptableSettingsSingleton(Of T As ScriptableSettings)

          Inherits ScriptableSettings
  inheritance:
  - System.Object
  - StansAssets.Foundation.ScriptableSettings
  inheritedMembers:
  - StansAssets.Foundation.ScriptableSettings.VersionCode
  - StansAssets.Foundation.ScriptableSettings.BasePath
  - StansAssets.Foundation.ScriptableSettings.PluginName
  - StansAssets.Foundation.ScriptableSettings.DocumentationUrl
  nameWithType.vb: ScriptableSettingsSingleton(Of T)
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
  fullName.vb: StansAssets.Foundation.ScriptableSettingsSingleton(Of T)
  name.vb: ScriptableSettingsSingleton(Of T)
- uid: StansAssets.Foundation.ScriptableSettingsSingleton`1.Instance
  commentId: P:StansAssets.Foundation.ScriptableSettingsSingleton`1.Instance
  id: Instance
  parent: StansAssets.Foundation.ScriptableSettingsSingleton`1
  langs:
  - csharp
  - vb
  name: Instance
  nameWithType: ScriptableSettingsSingleton<T>.Instance
  fullName: StansAssets.Foundation.ScriptableSettingsSingleton<T>.Instance
  type: Property
  source:
    id: Instance
    path: ''
    startLine: 113
  assemblies:
  - cs.temp.dll
  namespace: StansAssets.Foundation
  summary: "\nReturns a singleton class instance\nIf current instance is not assigned it will try to find an object of the instance type,\nin case instance already exists in a project. If not, new instance will be created,\nand saved under a <see cref=\"!:Instance.BasePath\"></see> location\n"
  example: []
  syntax:
    content: public static T Instance { get; }
    parameters: []
    return:
      type: '{T}'
    content.vb: Public Shared ReadOnly Property Instance As T
  overload: StansAssets.Foundation.ScriptableSettingsSingleton`1.Instance*
  nameWithType.vb: ScriptableSettingsSingleton(Of T).Instance
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
  fullName.vb: StansAssets.Foundation.ScriptableSettingsSingleton(Of T).Instance
- uid: StansAssets.Foundation.ScriptableSettingsSingleton`1.Save
  commentId: M:StansAssets.Foundation.ScriptableSettingsSingleton`1.Save
  id: Save
  parent: StansAssets.Foundation.ScriptableSettingsSingleton`1
  langs:
  - csharp
  - vb
  name: Save()
  nameWithType: ScriptableSettingsSingleton<T>.Save()
  fullName: StansAssets.Foundation.ScriptableSettingsSingleton<T>.Save()
  type: Method
  source:
    id: Save
    path: ''
    startLine: 133
  assemblies:
  - cs.temp.dll
  namespace: StansAssets.Foundation
  summary: "\nSaves instance to an editor database.\n"
  example: []
  syntax:
    content: public static void Save()
    content.vb: Public Shared Sub Save
  overload: StansAssets.Foundation.ScriptableSettingsSingleton`1.Save*
  nameWithType.vb: ScriptableSettingsSingleton(Of T).Save()
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: StansAssets.Foundation.ScriptableSettingsSingleton(Of T).Save()
- uid: StansAssets.Foundation.ScriptableSettingsSingleton`1.Version
  commentId: P:StansAssets.Foundation.ScriptableSettingsSingleton`1.Version
  id: Version
  parent: StansAssets.Foundation.ScriptableSettingsSingleton`1
  langs:
  - csharp
  - vb
  name: Version
  nameWithType: ScriptableSettingsSingleton<T>.Version
  fullName: StansAssets.Foundation.ScriptableSettingsSingleton<T>.Version
  type: Property
  source:
    id: Version
    path: ''
    startLine: 145
  assemblies:
  - cs.temp.dll
  namespace: StansAssets.Foundation
  summary: "\nSettings version.\n"
  example: []
  syntax:
    content: public static string Version { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared ReadOnly Property Version As String
  overload: StansAssets.Foundation.ScriptableSettingsSingleton`1.Version*
  nameWithType.vb: ScriptableSettingsSingleton(Of T).Version
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
  fullName.vb: StansAssets.Foundation.ScriptableSettingsSingleton(Of T).Version
- uid: StansAssets.Foundation.ScriptableSettingsSingleton`1.UpdateVersion(System.String)
  commentId: M:StansAssets.Foundation.ScriptableSettingsSingleton`1.UpdateVersion(System.String)
  id: UpdateVersion(System.String)
  parent: StansAssets.Foundation.ScriptableSettingsSingleton`1
  langs:
  - csharp
  - vb
  name: UpdateVersion(String)
  nameWithType: ScriptableSettingsSingleton<T>.UpdateVersion(String)
  fullName: StansAssets.Foundation.ScriptableSettingsSingleton<T>.UpdateVersion(System.String)
  type: Method
  source:
    id: UpdateVersion
    path: ''
    startLine: 153
  assemblies:
  - cs.temp.dll
  namespace: StansAssets.Foundation
  summary: "\nMethod will update and save version code\nReturns <code>true</code> in case version was update and <code>false</code> if version remained the same.\nThis method is meant to be used for an internal version check, to foldout if plugin was updated to a new version\nand run the necessary actions.\n"
  example: []
  syntax:
    content: public static bool UpdateVersion(string versionCode)
    parameters:
    - id: versionCode
      type: System.String
    return:
      type: System.Boolean
    content.vb: Public Shared Function UpdateVersion(versionCode As String) As Boolean
  overload: StansAssets.Foundation.ScriptableSettingsSingleton`1.UpdateVersion*
  nameWithType.vb: ScriptableSettingsSingleton(Of T).UpdateVersion(String)
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: StansAssets.Foundation.ScriptableSettingsSingleton(Of T).UpdateVersion(System.String)
references:
- uid: StansAssets.Foundation
  commentId: N:StansAssets.Foundation
  name: StansAssets.Foundation
  nameWithType: StansAssets.Foundation
  fullName: StansAssets.Foundation
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: StansAssets.Foundation.ScriptableSettings
  commentId: T:StansAssets.Foundation.ScriptableSettings
  parent: StansAssets.Foundation
  name: ScriptableSettings
  nameWithType: ScriptableSettings
  fullName: StansAssets.Foundation.ScriptableSettings
- uid: StansAssets.Foundation.ScriptableSettings.VersionCode
  commentId: F:StansAssets.Foundation.ScriptableSettings.VersionCode
  parent: StansAssets.Foundation.ScriptableSettings
  name: VersionCode
  nameWithType: ScriptableSettings.VersionCode
  fullName: StansAssets.Foundation.ScriptableSettings.VersionCode
- uid: StansAssets.Foundation.ScriptableSettings.BasePath
  commentId: P:StansAssets.Foundation.ScriptableSettings.BasePath
  parent: StansAssets.Foundation.ScriptableSettings
  name: BasePath
  nameWithType: ScriptableSettings.BasePath
  fullName: StansAssets.Foundation.ScriptableSettings.BasePath
- uid: StansAssets.Foundation.ScriptableSettings.PluginName
  commentId: P:StansAssets.Foundation.ScriptableSettings.PluginName
  parent: StansAssets.Foundation.ScriptableSettings
  name: PluginName
  nameWithType: ScriptableSettings.PluginName
  fullName: StansAssets.Foundation.ScriptableSettings.PluginName
- uid: StansAssets.Foundation.ScriptableSettings.DocumentationUrl
  commentId: P:StansAssets.Foundation.ScriptableSettings.DocumentationUrl
  parent: StansAssets.Foundation.ScriptableSettings
  name: DocumentationUrl
  nameWithType: ScriptableSettings.DocumentationUrl
  fullName: StansAssets.Foundation.ScriptableSettings.DocumentationUrl
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: StansAssets.Foundation.ScriptableSettingsSingleton`1.Instance*
  commentId: Overload:StansAssets.Foundation.ScriptableSettingsSingleton`1.Instance
  name: Instance
  nameWithType: ScriptableSettingsSingleton<T>.Instance
  fullName: StansAssets.Foundation.ScriptableSettingsSingleton<T>.Instance
  nameWithType.vb: ScriptableSettingsSingleton(Of T).Instance
  fullName.vb: StansAssets.Foundation.ScriptableSettingsSingleton(Of T).Instance
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: StansAssets.Foundation.ScriptableSettingsSingleton`1.Save*
  commentId: Overload:StansAssets.Foundation.ScriptableSettingsSingleton`1.Save
  name: Save
  nameWithType: ScriptableSettingsSingleton<T>.Save
  fullName: StansAssets.Foundation.ScriptableSettingsSingleton<T>.Save
  nameWithType.vb: ScriptableSettingsSingleton(Of T).Save
  fullName.vb: StansAssets.Foundation.ScriptableSettingsSingleton(Of T).Save
- uid: StansAssets.Foundation.ScriptableSettingsSingleton`1.Version*
  commentId: Overload:StansAssets.Foundation.ScriptableSettingsSingleton`1.Version
  name: Version
  nameWithType: ScriptableSettingsSingleton<T>.Version
  fullName: StansAssets.Foundation.ScriptableSettingsSingleton<T>.Version
  nameWithType.vb: ScriptableSettingsSingleton(Of T).Version
  fullName.vb: StansAssets.Foundation.ScriptableSettingsSingleton(Of T).Version
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: StansAssets.Foundation.ScriptableSettingsSingleton`1.UpdateVersion*
  commentId: Overload:StansAssets.Foundation.ScriptableSettingsSingleton`1.UpdateVersion
  name: UpdateVersion
  nameWithType: ScriptableSettingsSingleton<T>.UpdateVersion
  fullName: StansAssets.Foundation.ScriptableSettingsSingleton<T>.UpdateVersion
  nameWithType.vb: ScriptableSettingsSingleton(Of T).UpdateVersion
  fullName.vb: StansAssets.Foundation.ScriptableSettingsSingleton(Of T).UpdateVersion
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
