### YamlMime:ManagedReference
items:
- uid: StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton`1
  commentId: T:StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton`1
  id: PackageScriptableSettingsSingleton`1
  parent: StansAssets.Foundation.Patterns
  children:
  - StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton`1.Instance
  - StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton`1.Save
  langs:
  - csharp
  - vb
  name: PackageScriptableSettingsSingleton<T>
  nameWithType: PackageScriptableSettingsSingleton<T>
  fullName: StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton<T>
  type: Class
  source:
    id: PackageScriptableSettingsSingleton
    path: ''
    startLine: 145
  assemblies:
  - cs.temp.dll
  namespace: StansAssets.Foundation.Patterns
  summary: "\nPackage Scriptable Settings singleton pattern implementation.\n"
  example: []
  syntax:
    content: 'public abstract class PackageScriptableSettingsSingleton<T> : PackageScriptableSettings where T : PackageScriptableSettings'
    typeParameters:
    - id: T
    content.vb: >-
      Public MustInherit Class PackageScriptableSettingsSingleton(Of T As PackageScriptableSettings)
          Inherits PackageScriptableSettings
  inheritance:
  - System.Object
  - StansAssets.Foundation.Patterns.PackageScriptableSettings
  inheritedMembers:
  - StansAssets.Foundation.Patterns.PackageScriptableSettings.PackageName
  - StansAssets.Foundation.Patterns.PackageScriptableSettings.SettingsLocations
  nameWithType.vb: PackageScriptableSettingsSingleton(Of T)
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
  fullName.vb: StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton(Of T)
  name.vb: PackageScriptableSettingsSingleton(Of T)
- uid: StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton`1.Instance
  commentId: P:StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton`1.Instance
  id: Instance
  parent: StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton`1
  langs:
  - csharp
  - vb
  name: Instance
  nameWithType: PackageScriptableSettingsSingleton<T>.Instance
  fullName: StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton<T>.Instance
  type: Property
  source:
    id: Instance
    path: ''
    startLine: 155
  assemblies:
  - cs.temp.dll
  namespace: StansAssets.Foundation.Patterns
  summary: "\nReturns a singleton class instance\nIf current instance is not assigned it will try to find an object of the instance type,\nin case instance already exists in a project. If not, new instance will be created,\nand saved under a <xref href=\"StansAssets.Foundation.Patterns.PackageScriptableSettings.SettingsLocations\" data-throw-if-not-resolved=\"false\"></xref> location\n"
  example: []
  syntax:
    content: public static T Instance { get; }
    parameters: []
    return:
      type: '{T}'
    content.vb: Public Shared ReadOnly Property Instance As T
  overload: StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton`1.Instance*
  nameWithType.vb: PackageScriptableSettingsSingleton(Of T).Instance
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
  fullName.vb: StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton(Of T).Instance
- uid: StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton`1.Save
  commentId: M:StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton`1.Save
  id: Save
  parent: StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton`1
  langs:
  - csharp
  - vb
  name: Save()
  nameWithType: PackageScriptableSettingsSingleton<T>.Save()
  fullName: StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton<T>.Save()
  type: Method
  source:
    id: Save
    path: ''
    startLine: 176
  assemblies:
  - cs.temp.dll
  namespace: StansAssets.Foundation.Patterns
  summary: "\nSaves instance to an editor database.\n"
  example: []
  syntax:
    content: public static void Save()
    content.vb: Public Shared Sub Save
  overload: StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton`1.Save*
  nameWithType.vb: PackageScriptableSettingsSingleton(Of T).Save()
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton(Of T).Save()
references:
- uid: StansAssets.Foundation.Patterns
  commentId: N:StansAssets.Foundation.Patterns
  name: StansAssets.Foundation.Patterns
  nameWithType: StansAssets.Foundation.Patterns
  fullName: StansAssets.Foundation.Patterns
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: StansAssets.Foundation.Patterns.PackageScriptableSettings
  commentId: T:StansAssets.Foundation.Patterns.PackageScriptableSettings
  parent: StansAssets.Foundation.Patterns
  name: PackageScriptableSettings
  nameWithType: PackageScriptableSettings
  fullName: StansAssets.Foundation.Patterns.PackageScriptableSettings
- uid: StansAssets.Foundation.Patterns.PackageScriptableSettings.PackageName
  commentId: P:StansAssets.Foundation.Patterns.PackageScriptableSettings.PackageName
  parent: StansAssets.Foundation.Patterns.PackageScriptableSettings
  name: PackageName
  nameWithType: PackageScriptableSettings.PackageName
  fullName: StansAssets.Foundation.Patterns.PackageScriptableSettings.PackageName
- uid: StansAssets.Foundation.Patterns.PackageScriptableSettings.SettingsLocations
  commentId: P:StansAssets.Foundation.Patterns.PackageScriptableSettings.SettingsLocations
  parent: StansAssets.Foundation.Patterns.PackageScriptableSettings
  name: SettingsLocations
  nameWithType: PackageScriptableSettings.SettingsLocations
  fullName: StansAssets.Foundation.Patterns.PackageScriptableSettings.SettingsLocations
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton`1.Instance*
  commentId: Overload:StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton`1.Instance
  name: Instance
  nameWithType: PackageScriptableSettingsSingleton<T>.Instance
  fullName: StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton<T>.Instance
  nameWithType.vb: PackageScriptableSettingsSingleton(Of T).Instance
  fullName.vb: StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton(Of T).Instance
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton`1.Save*
  commentId: Overload:StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton`1.Save
  name: Save
  nameWithType: PackageScriptableSettingsSingleton<T>.Save
  fullName: StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton<T>.Save
  nameWithType.vb: PackageScriptableSettingsSingleton(Of T).Save
  fullName.vb: StansAssets.Foundation.Patterns.PackageScriptableSettingsSingleton(Of T).Save
