name: Build Documentation

on:
  repository_dispatch:
  push:
    branches:
      - documentation-ci-tes

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:

    # Checkout all repos
    - name: Checkout api.stansassets.com
      uses: actions/checkout@v2
      with:
        path: api.stansassets.com

    - name: Checkout com.stansassets.foundation
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.DOC_MGMT_TOKEN }}
        repository: StansAssets/com.stansassets.foundation
        path: com.stansassets.foundation

    - name: Checkout Native-Plugins
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.DOC_MGMT_TOKEN }}
        repository: StansAssets/Native-Plugins
        path: Native-Plugins

    - name: List work directory content
      run: ls
   
    # Clear existing documentation
    - name: Clear existing documentation
      run: |
        mv api.stansassets.com/docs/CNAME api.stansassets.com/
        rm -rf api.stansassets.com/docs/*
        mv api.stansassets.com/CNAME api.stansassets.com/docs/
    
    # Setup software
    - name: Get mono
      run: |
        apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        sudo apt-get update
        sudo apt-get install mono-complete --yes
    
    - name: Get docfx
      run: |
        curl -L https://github.com/dotnet/docfx/releases/latest/download/docfx.zip -o docfx.zip
        unzip -d .docfx docfx.zip
    
    # Build docs
    - name: Build docs
      run:  mono .docfx/docfx.exe api.stansassets.com/docfx-project/docfx.json
    
     # Commit and push
    - name: Commit and push
      run: |
        cd api.stansassets.com
        git config --global user.email "noreply@stansassets.com"
        git config --global user.name "Stan's Assets Automation"
        git add -A
        git status
        git commit -m "Automated docs update"
        git push
